# Generated by Django 5.1.6 on 2025-02-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMS_app', '0002_alter_show_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('show_number', 'theatre', 'show_time')},
        ),
    ]
