# Generated by Django 5.1.6 on 2025-02-25 08:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS_app', '0003_alter_show_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='show',
            name='ticket_price',
            field=models.PositiveIntegerField(default=150, validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nooftickets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('booking_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to='BMS_app.user')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_show', to='BMS_app.show')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_theatre', to='BMS_app.theatre')),
            ],
        ),
    ]
